name: benchmarks
channels:
  - conda-forge
dependencies:
  - make
  - cmake>=3.15
  - compilers
  - compiler-rt # sanitizers
  - llvm-openmp
  - libhwloc # for tbb
  - gmock
  - gtest
  - benchmark
  - matplotlib
  - numpy
  - seaborn
  - pandas
  - ipykernel
  # - libclang-cpp
  # - libcxx
  # - libstdcxx-ng
  # - libcxx
  # - libstdcxx-devel_linux-64
  # - gxx_linux-64 # C++ standard lib and gcc - https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html

